version: 0.0
os: linux
files:
  - source: app
    destination: /home/ubuntu/python-app/app
  - source: scripts
    destination: /home/ubuntu/python-app/scripts
  - source: requirements.txt
    destination: /home/ubuntu/python-app

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 20
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ubuntu
