version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Build stage - nothing to compile for Python."

artifacts:
  files:
    - app/**
    - requirements.txt
    - scripts/**
    - appspec.yml
